# Generated by Django 3.0.1 on 2021-02-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VedantaChemistry', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(blank=True, choices=[('class', 'class'), ('students', 'students'), ('document', 'document')], max_length=50, null=True),
        ),
    ]
