# Generated by Django 3.0.1 on 2021-02-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VedantaChemistry', '0007_auto_20210222_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
