# Generated by Django 3.0.1 on 2021-02-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VedantaChemistry', '0010_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
