# Generated by Django 3.0.1 on 2021-02-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VedantaChemistry', '0011_remove_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fee',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
